export const productData = [
    {
      "categoryId": "60d8db14e1d876001e6f62d2",
      "itemName": "Apples",
      "imageUrl": "https://picsum.photos/200",
      "itemDescription": "Fresh and juicy apples",
      "itemsQuantity": 100,
      "purchasePrice": 1,
      "salePrice": 2,
      "discount": null,
      "countryOfOrigin": "USA",
      "manufacturingDate": null,
      "expiryDate": "2023-07-31",
      "dateUpdated": "2023-06-15",
      "available": true
    },
    {
      "categoryId": "60d8db14e1d876001e6f62d3",
      "itemName": "Bread",
      "imageUrl": "https://picsum.photos/200",
      "itemDescription": "Freshly baked bread",
      "itemsQuantity": 50,
      "purchasePrice": 2,
      "salePrice": 3,
      "discount": null,
      "countryOfOrigin": "USA",
      "manufacturingDate": null,
      "expiryDate": "2023-07-05",
      "dateUpdated": "2023-06-20",
      "available": true
    },
    {
      "categoryId": "60d8db14e1d876001e6f62d4",
      "itemName": "Milk",
      "imageUrl": "https://picsum.photos/200",
      "itemDescription": "Fresh milk",
      "itemsQuantity": 75,
      "purchasePrice": 2,
      "salePrice": 3,
      "discount": null,
      "countryOfOrigin": "USA",
      "manufacturingDate": null,
      "expiryDate": "2023-07-15",
      "dateUpdated": "2023-06-10",
      "available": true
    },
    {
      "categoryId": "60d8db14e1d876001e6f62d2",
      "itemName": "Bananas",
      "imageUrl": "https://picsum.photos/200",
      "itemDescription": "Ripe bananas",
      "itemsQuantity": 30,
      "purchasePrice": 1.5,
      "salePrice": 2.5,
      "discount": null,
      "countryOfOrigin": "USA",
      "manufacturingDate": null,
      "expiryDate": "2023-07-31",
      "dateUpdated": "2023-07-05",
      "available": true
    },
    {
      "categoryId": "60d8db14e1d876001e6f62d3",
      "itemName": "Eggs",
      "imageUrl": "https://picsum.photos/200",
      "itemDescription": "Farm-fresh eggs",
      "itemsQuantity": 20,
      "purchasePrice": 3,
      "salePrice": 4,
      "discount": null,
      "countryOfOrigin": "USA",
      "manufacturingDate": null,
      "expiryDate": "2023-07-10",
      "dateUpdated": "2023-06-25",
      "available": true
    },
    {
      "categoryId": "60d8db14e1d876001e6f62d4",
      "itemName": "Chicken",
      "imageUrl": "https://picsum.photos/200",
      "itemDescription": "Fresh chicken",
      "itemsQuantity": 50,
      "purchasePrice": 5,
      "salePrice": 7,
      "discount": null,
      "countryOfOrigin": "USA",
      "manufacturingDate": null,
      "expiryDate": "2023-07-05",
      "dateUpdated": "2023-06-30",
      "available": true
    },
    {
      "categoryId": "60d8db14e1d876001e6f62d2",
      "itemName": "Oranges",
      "imageUrl": "https://picsum.photos/200",
      "itemDescription": "Juicy oranges",
      "itemsQuantity": 40,
      "purchasePrice": 1.5,
      "salePrice": 2.5,
      "discount": null,
      "countryOfOrigin": "USA",
      "manufacturingDate": null,
      "expiryDate": "2023-07-31",
      "dateUpdated": "2023-06-25",
      "available": true
    },
    {
      "categoryId": "60d8db14e1d876001e6f62d3",
      "itemName": "Yogurt",
      "imageUrl": "https://picsum.photos/200",
      "itemDescription": "Creamy yogurt",
      "itemsQuantity": 30,
      "purchasePrice": 1,
      "salePrice": 2,
      "discount": null,
      "countryOfOrigin": "USA",
      "manufacturingDate": null,
      "expiryDate": "2023-07-15",
      "dateUpdated": "2023-06-30",
      "available": true
    },
    {
      "categoryId": "60d8db14e1d876001e6f62d4",
      "itemName": "Tomatoes",
      "imageUrl": "https://picsum.photos/200",
      "itemDescription": "Fresh tomatoes",
      "itemsQuantity": 60,
      "purchasePrice": 1.5,
      "salePrice": 2.5,
      "discount": null,
      "countryOfOrigin": "USA",
      "manufacturingDate": null,
      "expiryDate": "2023-07-31",
      "dateUpdated": "2023-06-20",
      "available": true
    },
    {
      "categoryId": "60d8db14e1d876001e6f62d3",
      "itemName": "Butter",
      "imageUrl": "https://picsum.photos/200",
      "itemDescription": "Creamy butter",
      "itemsQuantity": 25,
      "purchasePrice": 2.5,
      "salePrice": 4,
      "discount": null,
      "countryOfOrigin": "USA",
      "manufacturingDate": null,
      "expiryDate": "2023-07-31",
      "dateUpdated": "2023-06-15",
      "available": true
    }
  ]
  